### ISSUE TITLE
Cannot run application including the package on device

### ISSUE THREAD

**Issue by vimception** [Flash3001/Xamarin.Swift22.Support#1]
Hello,

When building an application including this package outside an IDE (on command line, CI) for device, the ipa refuses to run. Inspecting this *.app file with codesign  ($ codesign -vvvv ....app) reveals:

<appname>.app: a sealed resource is missing or invalid
file missing: <path>/<appname>.app/SwiftFrameworksSimulator/libswiftFoundation.dylib
....

So apparently the _CodeSignature/CodeResources contains entries for the SwiftFrameworksSimulator libraries, but they are not available in the app package.

When looking at this build target:

https://github.com/Flash3001/Xamarin.Swift22.Support/blob/master/Xamarin.Swift22.Support/build/Xamarin.Swift22.Support.targets#L15

$(CodesignDependsOn);
_RemoveExtraLibs;

I see first all Codesign steps are done during build, and then the SwiftFrameworksSimulator files are removed, which I assume leads to this problem. I'm not a MSBuild targets expert, but I think reversing these two lines would solve this problem.

What's your take on this?
Thanks.

**Comment by Flash3001** [comment]
If we invert those two lines Xamarin Studio will try to sign the libraries after they are deleted. 

So I delete them after they are signed because the app is going to be signed again when you use 'Archive for Publishing' and 'Sign and Distribute...'

The ideal solution would be to remove the files before Xamarin generate the list of itens to Sign. But I couldn't find it.

**Comment by jamie94bc** [comment]
I believe I might have fixed this in #2 😄

**Comment by Flash3001** [comment]
@langsweirdt Issue has been fixed and package updated for versions 2.2, 2.3 and 3.0 of the library.

Files now are removed before Xamarin list them to be signed. 
https://github.com/Flash3001/Xamarin.Swift22.Support/blob/master/Xamarin.Swift22.Support/build/Xamarin.Swift22.Support.targets#L13
